# Generated by Django 3.1.4 on 2020-12-21 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular accommodation.', primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Insert an accommodation type.', max_length=150)),
                ('description', models.TextField(help_text='Enter a description of the accommodation type.', max_length=2000)),
                ('price_from', models.DecimalField(decimal_places=2, help_text='Insert price from.', max_digits=10)),
                ('price_to', models.DecimalField(decimal_places=2, help_text='Insert price to.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an animal kind (e.g. Leopard, Elephant)', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular park.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Insert where is the park located.', max_length=150)),
                ('ideal_months', models.CharField(choices=[('0', "Month doesn't matter."), ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='0', help_text='Ideal months for visit.', max_length=20)),
                ('description', models.TextField(help_text='Enter a description of the park.', max_length=2000)),
                ('animals', models.ManyToManyField(help_text='Select animals for this park.', to='catalog.Animal')),
            ],
        ),
    ]
