# Generated by Django 3.1.4 on 2021-01-05 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210102_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular feedback.', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Enter your feedback.', max_length=2000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
            ],
        ),
    ]
