# Generated by Django 3.1.4 on 2021-01-06 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
