# Generated by Django 3.1.4 on 2021-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
