# Generated by Django 3.1.4 on 2021-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210111_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='message_for_us',
            field=models.TextField(blank=True, help_text='Enter a message of us, if u want.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='trip',
            name='days',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], help_text='Select how many days you wish to stay in this park.'),
        ),
    ]
