# Generated by Django 3.1.4 on 2021-01-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210114_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='number_of_people',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='Select how many people. (Can be changed later)', null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='recommended',
            field=models.BooleanField(default=False, help_text='Is this a recommended trip by agency?'),
        ),
    ]
