# Generated by Django 3.1.6 on 2021-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210120_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a short description for this day. (e.g. Day 1: Arusha)', max_length=150)),
                ('description', models.TextField(help_text='Enter a programme for this day.', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='name',
            field=models.CharField(default='', help_text='Enter a name for this recommended expedition. (e.g. 5-day safari)', max_length=150),
            preserve_default=False,
        ),
    ]
