# Generated by Django 3.1.6 on 2021-02-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210222_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter some name for easier organization. (e.g. 5-day safari itinerary)', max_length=150)),
                ('description', models.TextField(help_text='Enter a short description for this expedition programme.', max_length=2000)),
                ('daily_plans', models.ForeignKey(help_text='Select daily plans.', on_delete=django.db.models.deletion.CASCADE, to='catalog.dailyplan')),
            ],
        ),
    ]
