# Generated by Django 3.1.6 on 2021-02-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='daily_plans',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='dailyPlans',
            field=models.ManyToManyField(help_text='Select daily plans.', to='catalog.DailyPlan'),
        ),
    ]
