# Generated by Django 3.1.6 on 2021-02-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210222_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.itinerary'),
        ),
    ]
