# Generated by Django 3.1.6 on 2021-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_expedition_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a name for this recommended expedition. (e.g. 5-day safari)', max_length=150),
        ),
    ]
