# Generated by Django 3.1.6 on 2021-02-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210223_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.itinerary'),
        ),
    ]
