# Generated by Django 3.1.6 on 2021-02-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210223_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number in international format. (e.g. +421944123132)', max_length=16),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='message_for_us',
            field=models.TextField(blank=True, help_text='Enter a message for us, if u want.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.ForeignKey(help_text='Select what accommodation you prefer.', on_delete=django.db.models.deletion.CASCADE, to='catalog.accommodation'),
        ),
    ]
