# Generated by Django 3.1.6 on 2021-03-20 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_customer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_of_trip',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
