# Generated by Django 3.1.6 on 2021-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20210407_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='lable',
            field=models.CharField(default='skuska', help_text='Enter an identification for this day. (e.g. 5-day: Day 1)', max_length=150),
            preserve_default=False,
        ),
    ]
