# Generated by Django 3.1.4 on 2021-04-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_dailyplan_lable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(help_text='Enter a description of the park.', max_length=3500),
        ),
    ]
