# Generated by Django 3.1.4 on 2021-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20210420_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(help_text='Enter a description of the park.', max_length=5000),
        ),
    ]
