# Generated by Django 3.1.4 on 2021-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20210420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the accommodation type.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insert price from.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insert price to.', max_digits=10),
        ),
    ]
