# Generated by Django 3.1.4 on 2021-04-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210421_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyplan',
            old_name='lable',
            new_name='label',
        ),
        migrations.AddField(
            model_name='park',
            name='safari',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='days',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='Select how many days you wish to stay in this park.'),
        ),
    ]
