# Generated by Django 3.1.4 on 2021-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20210424_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='trips',
            field=models.ManyToManyField(help_text='Select safari trips you wish to visit.', to='catalog.Trip'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='dailyPlans',
            field=models.ManyToManyField(blank=True, help_text='Select daily plans.', to='catalog.DailyPlan'),
        ),
    ]
