# Generated by Django 3.1.4 on 2021-04-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20210427_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='days_up_to',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='Select how many days you wish to stay in this park.', null=True),
        ),
    ]
