# Generated by Django 3.1.4 on 2021-04-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20210429_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='single_trip',
            field=models.BooleanField(null=True),
        ),
    ]
