# Generated by Django 3.1.4 on 2021-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20210429_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a short description for this expedition.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='single_trip',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
