# Generated by Django 3.1.4 on 2021-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20210505_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default='profile_imgs/anonymous-user.png', upload_to='profile_imgs/'),
        ),
    ]
