# Generated by Django 3.1.4 on 2021-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20210517_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hidden_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='hidden_phone',
            field=models.BooleanField(default=True),
        ),
    ]
