# Generated by Django 3.1.6 on 2021-06-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_expedition_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
